version: "3.9"
services:
  db:
    image: arangodb/arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    ports:
      - "8529:8529"
    volumes:
      - arangodb_data:/var/lib/arangodb3
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - ARANGO_DB=prod-db
      - ARANGO_USER=prod-user
      - ARANGO_PASSWORD=secure-pass
      - ARANGO_HOST=db:8529
      - JWT_SECRET=S4Ordc+OvQx3AB1yZUIaX5YutUph9P1ZLZ5WJNdaD3KkTCWSxOHzPNPMS6dZPl6zAdOji/gmu9+mGvscTqbydw==
      - JWT_EXPIRATION_MS=86400000
      - FILE_STORAGE_PATH=/data/store
      - ARANGO_DUMP=/usr/bin/arangodump
      - ARANGO_RESTORE=/usr/bin/arangorestore
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./store:/data/store
    depends_on:
      - db

volumes:
  arangodb_data:
  # TODO: frontend