version: "3.9"
services:
  db:
    image: arangodb/arangodb:3.12.4
    environment:
      - ARANGO_NO_AUTH=1
    networks:
      - internal-net
    volumes:
      - arangodb_data:/var/lib/arangodb3
    restart: unless-stopped

  backend:
    build: ./backend
    restart: unless-stopped
    networks:
      - internal-net
    ports:
      - "8080:8080"
    environment:
      - ARANGO_DB=prod-db
      - ARANGO_USER=prod-user
      - ARANGO_PASSWORD=secure-pass
      - ARANGO_HOST=db:8529
      - JWT_SECRET=S4Ordc+OvQx3AB1yZUIaX5YutUph9P1ZLZ5WJNdaD3KkTCWSxOHzPNPMS6dZPl6zAdOji/gmu9+mGvscTqbydw==
      - JWT_EXPIRATION_MS=86400000
      - FILE_STORAGE_PATH=/data/store
      - ARANGO_DUMP=/usr/bin/arangodump
      - ARANGO_RESTORE=/usr/bin/arangorestore
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - store:/data/store
    depends_on:
      - db
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"

volumes:
  arangodb_data:
  store:

networks:
  internal-net:
    driver: bridge