version: "3.9"
services:
  db:
    image: arangodb/arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    ports:
      - "8529:8529"
    volumes:
      - /tmp/arangodb_dev_data:/var/lib/arangodb3
    restart: unless-stopped

  backend:
    restart: unless-stopped
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - ARANGO_DB=prod-db
      - ARANGO_USER=prod-user
      - ARANGO_PASSWORD=secure-pass
      - ARANGO_HOST=arangodb:8529
      - JWT_SECRET=your-very-secure-prod-secret
      - JWT_EXPIRATION_MS=86400000
      - FILE_STORAGE_PATH=/data/store
      - ARANGO_DUMP=/usr/bin/arangodump
      - ARANGO_RESTORE=/usr/bin/arangorestore
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./store:/data/store
    depends_on:
      - db
