services:
  db:
    image: arangodb/arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    ports:
      - "8529:8529"
    volumes:
      - /tmp/arangodb_dev_data:/var/lib/arangodb3
    restart: unless-stopped
