/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createRepository"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["authRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/{repoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateRepository"];
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRepositories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUserInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/{repoId}/branches/{branchId}/commits/{commitId}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["viewRepository"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateRepositoryRequest: {
            /** Format: uri */
            originalLink: string;
            name: string;
            /** @enum {string} */
            visibility: "PUBLIC" | "PROTECTED" | "PRIVATE";
        };
        RepositoryDto: {
            id?: string;
            name?: string;
            owner?: string;
            defaultBranch?: string;
            /** Format: uri */
            originalLink?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        AuthRegisterRequest: {
            username: string;
            email?: string;
            password: string;
        };
        UserDto: {
            id?: string;
            username?: string;
            email?: string;
            /** @enum {string} */
            visibility?: "PUBLIC" | "PRIVATE";
            /** Format: date-time */
            createdAt?: string;
            isAdmin?: boolean;
        };
        GrantedAuthority: {
            authority?: string;
        };
        UserDetailsWithId: {
            password?: string;
            username?: string;
            authorities?: components["schemas"]["GrantedAuthority"][];
            accountNonExpired?: boolean;
            accountNonLocked?: boolean;
            credentialsNonExpired?: boolean;
            enabled?: boolean;
            id?: string;
        };
        BranchDto: {
            id?: string;
            name?: string;
            repo?: string;
            isDefault?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        CommitDto: {
            id?: string;
            branch?: string;
            hash?: string;
            author?: string;
            email?: string;
            message?: string;
            /** Format: int32 */
            filesChanged?: number;
            /** Format: int32 */
            linesAdded?: number;
            /** Format: int32 */
            linesRemoved?: number;
            /** Format: date-time */
            createdAt?: string;
            rootFiles?: components["schemas"]["CommitFileDto"][];
        };
        CommitFileDto: {
            id?: string;
            name?: string;
            /** @enum {string} */
            type?: "DIRECTORY" | "FILE";
            hash?: string;
            commit?: string;
            parent?: string;
        };
        RepositoryViewDto: {
            owner?: components["schemas"]["ShortUserDto"];
            repository?: components["schemas"]["RepositoryDto"];
            branches?: string[];
            branch?: components["schemas"]["BranchDto"];
            commit?: components["schemas"]["CommitDto"];
        };
        ShortUserDto: {
            id?: string;
            username?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createRepository: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRepositoryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RepositoryDto"];
                };
            };
        };
    };
    authRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserDto"];
                };
            };
        };
    };
    updateRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RepositoryDto"];
                };
            };
        };
    };
    getUserInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserDto"];
                };
            };
        };
    };
    getRepositories: {
        parameters: {
            query?: {
                currentUser?: components["schemas"]["UserDetailsWithId"];
            };
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RepositoryDto"][];
                };
            };
        };
    };
    getCurrentUserInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserDto"];
                };
            };
        };
    };
    viewRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repoId: string;
                branchId: string;
                commitId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RepositoryViewDto"];
                };
            };
        };
    };
}
