spring:
  application:
    name: backend

logging:
  level:
    com.arangodb.internal.net.Communication: DEBUG

arangodb:
  spring:
    data:
      database: ${ARANGO_DB:sweetgit-db}
      user: ${ARANGO_USER:root}
      password: ${ARANGO_PASSWORD:}
      hosts: ${ARANGO_HOST:localhost:8529}

springdoc:
  api-docs:
    path: /openapi.json
  swagger-ui:
    path: /docs

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}

app:
  file-storage:
    path: ${FILE_STORAGE_PATH:/app/store}
  backup:
    executable:
      dump: ${ARANGO_DUMP:/usr/bin/arangodump}
      restore: ${ARANGO_RESTORE:/usr/bin/arangorestore}
