spring:
  application:
    name: backend

logging:
  level:
    com.arangodb.internal.net.Communication: DEBUG

arangodb:
  spring:
    data:
      database: sweetgit-db
      user: root
      password: ''
      hosts: localhost:8529

springdoc:
  api-docs:
    path: /openapi.json
  swagger-ui:
    path: /docs

jwt:
  secret: 
  expiration-ms: 86400000

app:
  file-storage:
    path: 
  backup:
    executable:
      dump: 
      restore: /
