spring:
  application:
    name: backend

logging:
  level:
    com.arangodb.internal.net.Communication: DEBUG

arangodb:
  spring:
    data:
      database: sweetgit-db
      user: root
      password: ''
      hosts: localhost:8529

springdoc:
  api-docs:
    path: /openapi.json
  swagger-ui:
    path: /docs

jwt:
  secret: saaI9zMtell9xbas423Tm0AirflZjD5NDbSKut3O2RSKT3WX+B42/Rr+YGb8S4uXRf7wp8HWNMcy5TsLR+yV/mGqpaVP/mt0N/jShm4323Y= # todo change on prod
  expiration-ms: 86400000

app:
  file-storage:
    path: /Users/raregod/nosql1h25-asttrees/store
  backup:
    executable:
      dump: /Users/raregod/backDumpRestore/bin/arangodump
      restore: /Users/raregod/backDumpRestore/bin/arangorestore
